
name: ea-downscaling
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - xarray>=2024.6.0
  - numpy>=1.26
  - pandas>=2.2
  - dask>=2024.5.0
  - xclim>=0.47.0
  - xesmf>=0.8.6
  - netcdf4>=1.6
  - zarr>=2.18
  - cftime>=1.6
  - regionmask>=0.11.0
  - rasterio>=1.3
  - rioxarray>=0.15
  - matplotlib>=3.8
  - cartopy>=0.23
  - geopandas>=1.0
  - pyproj>=3.6
  - scipy>=1.12
  - tqdm>=4.66
  - pip
  - pip:
      - pooch>=1.8
      - pyyaml>=6.0
